### ISSUE TITLE
Include broad .gitignore

### ISSUE THREAD

**Issue by maresb** [mysto/python-fpe#10]
Having a broad range of environment-specific stuff is good in my experience. That allows contributors to use whatever tools they want without going through the mess we saw with the `.idea/` files. If the Python package is set up properly, the `.gitignore` won't be included in the PyPI distribution.

In the end, it won't prevent you from `git add`ing files. It just prevents `git` from suggesting irrelevant files to add.

I read over @PuspenduBanerjee's `.gitignore` and it looks perfectly good to me. I'd recommend restoring it. Or at the very least find a standard Python-oriented `.gitignore` from somewhere.

**Comment by bschoening** [comment]
I did add a .gitignore which uses a wildcard to excludes all dot files, except for the two included here.  I copied the technique from a stackoverflow article.  Let me know if that looks about right.

**Comment by maresb** [comment]
There are many dot files that one typically wants to add to git, e.g. `.pre-commit-config.yaml` and also many non dots that one wants to exclude, e.g. `__pycache__`. The minimalist technique is just not very good.

**Comment by bschoening** [comment]
Dot file are hidden files, so excluding them by default seems reasonable.  The package currently includes only one dot file (other than .getignore itself), and like you said it won't prevent you from git adding files.

Other files like __pycache__ can certainly be added to .getignore and I've done so with many of the usual suspects.

**Comment by maresb** [comment]
Looks much better now, thanks!
