### ISSUE TITLE
Ff3-1 aes256 key and tweak Generation 

### ISSUE THREAD

**Issue by Kkeller83** [mysto/python-fpe#26]
Thanks for this! I'm using your library atm to protect some testing data and it works great. But how can I generate an ff3-1 key and tweak for usage with aes256 block cipher please?

**Comment by bschoening** [comment]
There are examples of keys and tweaks in the unit tests (ff3_test.py).  For FF3-1 the tweaks need to be 56 bits.

**Comment by Kkeller83** [comment]
I'm using the keys from the examples for my own tests yep. But if I want to put ff3 into production I'll need a way to generate a new key.

**Comment by Kkeller83** [comment]
Nevermind, after reading how ff3 actually works I understand that I can just use use any aes256 key. works ok

**Comment by Kkeller83** [comment]
I'm using the keys from the examples for my own tests yep. But if I want to
put ff3 into production I'll need a way to generate a new key.

**Comment by bschoening** [comment]
Hi, you're probalby looking for a Key Management System (KMS).  That would be outside the scope of the FF3 encryption library.  Java keytool might be one of the easiest to use and there is a python interface available with 
[pyjks](https://github.com/kurtbrose/pyjks). There may be others more suited to your use case.
