### ISSUE TITLE
Could you please provide the FPE-FF1 code?

### ISSUE THREAD

**Issue by liyangzbx** [mysto/python-fpe#27]

**Comment by bschoening** [comment]
I'd be interested to know your interest in the FF1 over FF3.

Microfocus claims a patent on the FF1 algorithm and requires a license for its use. The license cost is revenue based, in the range of 2%. The license does not permit the use of FF1 in open source code, and using such open source code would require a license.

I'm aware people have implemented FF1 in open source without a license.  However, I have corresponded with Microfocus on this topic and such use could be subject to litigation.
