### ISSUE TITLE
FF1

### ISSUE THREAD

**Issue by sfc-gh-kkeller** [mysto/python-fpe#28]
I started using the FF3-1 implementation recently and its super cool. However I was approached if FF1 would also be an option. 
I was told its "better" as in "more secure" than FF3-1. 

I dont know if that is true, but I certainly know that I can not implement FF1 in Python now. 

Would it be something to consider to also add FF1 support please?

**Comment by bschoening** [comment]
Hi, thanks for your suggestion (and any stars).  This was discussed earlier in this issue https://github.com/mysto/python-fpe/issues/27. Unfortunately, there are patent claims by Microfocus on FF1.  

A flaw was discovered in FF3 and it was replaced by a small update in FF3-1.  I'm not aware of any claims that FF1 is more secure, just that it never had an algorithmic property that needed correction.  That said, both FF1 and FF3-1 were revised to increase the minimum domain size to 1M as the earlier domain of 1,000 was found to be vulnerable.

**Comment by sfc-gh-kkeller** [comment]
Thanks for the quick answer. Ok that clears it all up for me. Appreciate it
