### ISSUE TITLE
Not an issue, actually

### ISSUE THREAD

**Issue by polfosol** [mysto/python-fpe#29]
I just wanted to let you know that I have used some of your test vectors to verify my C-implementation of the FPE algorithms. Of course I have mentioned the source and credit. Please feel free to check out the `testvectors` folder of [this repository](https://github.com/polfosol/micro-AES) and inform me of any issues.

Cheers

**Comment by bschoening** [comment]
Hi, nice to hear that it was useful to you. The FF3-1 draft test vectors are public domain, but have yet to be officially published by NIST.  Just keep an eye out for whenever the official ones drop.
