### ISSUE TITLE
Want to make sure this algorithm will not generate collisions

### ISSUE THREAD

**Issue by adrenaline681** [mysto/python-fpe#31]
Hello, I'm using this module to convert the id of a order to a 12-digit confirmation number, for example:

Order ID 1 = 000000000001  -->  457845269874  
Order ID 2 = 000000000002  -->  784378928745

My code goes like this:

```
key = 'C4D91A3F7B61834E90FD72563CACF01E'
tweak = 'ABD39280979565'
c = FF3Cipher(key, tweak)

order_id = 1
order_id_padded = f'{order_id:012}'
confirmation_number = c.encrypt(order_id_padded)
```

I assume that as long as I don't change the key or the tweak I should not have any collision issues of two order ids generating the same confirmation number. Is this correct?

Thanks for your time

**Comment by bschoening** [comment]
Yes, the source data and protected data have a one-to-one relationship such that collisions will not occur with format preserving encryption. If you consider decryption, it would not work if collisions occurred.
