### ISSUE TITLE
Leading / trailing zeros causes `ValueError` during .encrypt

### ISSUE THREAD

**Issue by briangow** [mysto/python-fpe#32]
When I do the following:

```
c = FF3Cipher(key, tweak, radix=36)
my_str = '100000'
fpe = c.encrypt(my_str)
```

I get this error:
`ValueError: string 000 is not within base/radix`

The same error will occur with `my_str = '000001'` but does not occur with `my_str = '100001'`. Is this expected? I don't see anything in the specification about a limitation on leading / trailing zeros.

**Comment by bschoening** [comment]
Hi, 
I'm not able to reproduce this problem.  It works fine for me.  Is this with the latest version 1.0.1, trunk or something else?

**Comment by briangow** [comment]
Thanks for the quick response. It looks like when I rebuilt my environment I was using a forked version of your code: 

https://github.com/PuspenduBanerjee/python-fpe
https://pypi.org/project/pyFPE/

When I change to:

https://pypi.org/project/ff3/

the error no longer occurs.
