### ISSUE TITLE
Using the use of logging.debug() in FF3 breaks our structured logging system

### ISSUE THREAD

**Issue by adrenaline681** [mysto/python-fpe#33]
We are currently using structlog in our application and I noticed a weird bug when using the FF3 package.

As soon as FF3 gets used in our code our structured logging breaks. This seems to be due to the use of logging.debug() in the FF3 package. We believe that its because logging.debug() uses the root logger. 

Here an example of the use of this function in the FF3 code:
`logging.debug(f"Tweak: {tweak}, tweakBytes:{tweakBytes.hex()}")`

We suggest switching it to using a named logger like this:
```
logger = logging.getLogger(__name__) 
logger.debug(f"Tweak: {tweak}, tweakBytes:{tweakBytes.hex()}")
```

**Comment by bschoening** [comment]
Thanks for this, I see the python docs say "Note that Loggers should NEVER be instantiated directly, but always through the module-level function logging.getLogger(name)."   https://docs.python.org/3/library/logging.html

I'll look to fix this, or feel free to provide a PR.

**Comment by jrobichaud** [comment]
@bschoening 

This quote:

> Note that Loggers should NEVER be instantiated directly, but always through the module-level function logging.getLogger(name).

refers to do this:

```python
logger = logging.getLogger(name)
```

and NEVER this:
```python
logger = logging.Logger()
```

The code of FF3 is not wrong in that matter. 

However, I strongly believe it is a better practice to use a logger through `logging.getLogger(name)` rather than the `root` logger in python modules. 

I would still recommend to do the fix, but for the good reason.
